import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { StorageItem } from "./storageService";

interface User {
  email?: string;
  user_metadata?: {
    full_name?: string;
    avatar_url?: string;
  };
}

export const exportToPdf = (items: StorageItem[], user: User | null) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header Background
  doc.setFillColor(0, 122, 255); // Apple Blue
  doc.rect(0, 0, pageWidth, 40, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("ResearchMate Report", 14, 25);

  // User Info (Right Aligned)
  if (user) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const name = user.user_metadata?.full_name || user.email || "User";
    const email = user.email || "";
    const date = new Date().toLocaleDateString();

    doc.text(`Generated by: ${name}`, pageWidth - 14, 18, { align: "right" });
    doc.text(`Date: ${date}`, pageWidth - 14, 24, { align: "right" });
    if (email) {
      doc.text(email, pageWidth - 14, 30, { align: "right" });
    }
  }

  // Metadata Section
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(10);
  doc.text(`Total Items: ${items.length}`, 14, 50);

  // Table Data Preparation
  const tableData = items.map((item) => [
    item.citation || item.sourceTitle || "Untitled Source",
    item.aiSummary || item.note || item.text.substring(0, 100) + "...",
    item.tags?.join(", ") || "-",
    item.sourceUrl || "-",
  ]);

  // Generate Table
  autoTable(doc, {
    startY: 55,
    head: [["Source / Citation", "Summary / Note", "Tags", "Link"]],
    body: tableData,
    theme: "striped",
    headStyles: { fillColor: [0, 122, 255], textColor: 255 },
    styles: { fontSize: 9, cellPadding: 3, overflow: "linebreak" },
    columnStyles: {
      0: { cellWidth: 50 }, // Citation
      1: { cellWidth: 70 }, // Summary
      2: { cellWidth: 30 }, // Tags
      3: { cellWidth: 40 }, // Link
    },
    didDrawPage: (data: any) => {
      // Footer
      const pageCount = doc.internal.pages.length - 1;
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Page ${pageCount}`,
        data.settings.margin.left,
        doc.internal.pageSize.height - 10,
      );
    },
  });

  // Save PDF
  const filename = `researchmate_report_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
};

export const exportSingleItemToPdf = (item: StorageItem) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header Background
  doc.setFillColor(0, 122, 255); // Apple Blue
  doc.rect(0, 0, pageWidth, 30, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("ResearchMate Item", 14, 20);

  let yPos = 40;

  // Citation (Boxed)
  if (item.citation) {
    doc.setFillColor(245, 247, 250);
    doc.setDrawColor(200, 200, 200);
    doc.rect(14, yPos, pageWidth - 28, 25, "FD"); // Fill and Draw

    doc.setTextColor(0, 50, 100);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("CITATION", 18, yPos + 8);

    doc.setTextColor(50, 50, 50);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(11);

    // Split text to fit
    const splitCitation = doc.splitTextToSize(item.citation, pageWidth - 40);
    doc.text(splitCitation, 18, yPos + 18);

    yPos += 35;
  }

  // Source Info
  if (item.sourceTitle || item.sourceUrl) {
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");

    if (item.sourceTitle) {
      doc.text(`Source: ${item.sourceTitle}`, 14, yPos);
      yPos += 6;
    }
    if (item.sourceUrl) {
      doc.setTextColor(0, 122, 255);
      doc.textWithLink("Link to Source", 14, yPos, { url: item.sourceUrl });
      yPos += 10;
    }
  }

  yPos += 5;

  // Summary (if exists)
  if (item.aiSummary) {
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("AI Summary", 14, yPos);
    yPos += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);

    const splitSummary = doc.splitTextToSize(item.aiSummary, pageWidth - 28);
    doc.text(splitSummary, 14, yPos);
    yPos += splitSummary.length * 5 + 10;
  }

  // Original Text (if summary exists, label it "Original Text", else just "Content")
  const label = item.aiSummary ? "Original Selection" : "Content";
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(label, 14, yPos);
  yPos += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  const splitText = doc.splitTextToSize(item.text, pageWidth - 28);
  doc.text(splitText, 14, yPos);

  // Footer with Date
  const date = new Date(item.createdAt).toLocaleString();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Saved on: ${date}`, 14, doc.internal.pageSize.height - 10);

  // Save PDF
  const safeTitle = (item.sourceTitle || "item")
    .replace(/[^a-z0-9]/gi, "_")
    .substring(0, 20);
  doc.save(`researchmate_${safeTitle}.pdf`);
};

export const exportSingleItemToJson = (item: StorageItem) => {
  const dataStr =
    "data:text/json;charset=utf-8," +
    encodeURIComponent(JSON.stringify(item, null, 2));
  const downloadAnchorNode = document.createElement("a");
  downloadAnchorNode.setAttribute("href", dataStr);
  downloadAnchorNode.setAttribute(
    "download",
    `researchmate_item_${item.id.substring(0, 8)}.json`,
  );
  document.body.appendChild(downloadAnchorNode);
  downloadAnchorNode.click();
  downloadAnchorNode.remove();
};
